urld <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(urld, "Dataset.zip")
unzip("Dataset.zip")
household <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
household$Date <- as.Date(household$Date, "%d/%m/%Y")
household$Time <- strptime(household$Time, "%H:%M:%S")
household$Time <- sub(".*\\s+", "",  household$Time)
filteredset <- subset(household, Date == "2007-02-01" | Date == "2007-02-02")
filteredset$Global_active_power <- as.numeric(as.character(filteredset$Global_active_power))
filteredset$Global_reactive_power <- as.numeric(as.character(filteredset$Global_reactive_power))
filteredset$Time <- as.POSIXct(paste(filteredset$Date,filteredset$Time), "%Y-%m-%d %H:%M:%S")
png(filename = "plot4.png", width = 480, height = 480)
par(mfcol = c(2,2))
with(filteredset, plot(Time, Global_active_power, type ="l", ylab = "Global Active Power (kilowatts)"))
with(filteredset, plot(Time, Sub_metering_1, type ="l", ylab = "Energy sub metering"))
with(filteredset, lines(Time, Sub_metering_2, type ="l", col = "red"))
with(filteredset, lines(Time, Sub_metering_3, type ="l", col = "blue"))
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black", "red", "blue"), lty = c(1,1,1))
with(filteredset, plot(Time, Voltage, type ="l", ylab = "Voltage", xlab = "datetime"))
with(filteredset, plot(Time, Global_reactive_power, type ="l", ylab = "Global reactive power", xlab = "datetime"))
dev.off()